### ISSUE TITLE
Why are both Yarn and NPM required?

### ISSUE THREAD

**Issue by azankl** [sepetab/Plugin_Biodata-HPO-#5]
As far as I understand it, Yarn and NPM are both package managers, why would you need both? Also, when I build the extension from source, I get a warning that 'it is advised not to mix package managers to avoid resolution inconsistencies...'
I also get lots of errors when running 'yarn install', see log attached. 
[Log at 2020-08-27 9-52-44 am.txt](https://github.com/sepetab/Plugin_Biodata-HPO-/files/5133211/Log.at.2020-08-27.9-52-44.am.txt)

**Comment by anthonyaxu** [comment]
Hi Andreas, 

Yes, I believe that is correct. Looking at our documentation again, I believe we have made an error. Instead of doing both 'yarn install' and 'npm install', it should just be 'yarn install' to install the dependencies for the plugin. I have updated the instructions in the README.md section to reflect this. You may have to clone the repo again to ensure there are no conflicts with the previous dependency installations. Hopefully, this solves the Vue packages mismatch as well. 

As for why both yarn and npm are used, I believe that yarn is used to install the dependencies initially while 'npm run build' is used every time there are changes to the source files create a package that is able to be loaded into Chrome. This is similar to how the original prototype worked. 

Apologies for the error and please let us know if there is anything else. 

Anthony
