### ISSUE TITLE
'Accessing non-existent property' warnings when building 

### ISSUE THREAD

**Issue by azankl** [sepetab/Plugin_Biodata-HPO-#7]
I get a lot of 'Accessing non-existent property' warnings when running 'yarn run build', see log attached.
[yarn_log.txt](https://github.com/sepetab/Plugin_Biodata-HPO-/files/5141658/yarn_log.txt)

**Comment by anthonyaxu** [comment]
I am having trouble trying to recreate the issue but I believe that it this is occurring because the `shelljs` package is not updated. I have updated `shelljs` from `0.7.4` to the latest version `0.8.4`. 

If the new packages do not fix this error, let us know if `npx cross-env NODE_OPTIONS="--trace-warnings" yarn build` returns a particular package.

**Comment by azankl** [comment]
Building without errors now.
